"""updating column name typo in rps

Revision ID: 207afec267d1
Revises: 610de6abb3b0
Create Date: 2024-12-11 22:30:54.403185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207afec267d1'
down_revision = '610de6abb3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_restaurant_pizzas_restuarant_id_restaurants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), 'restaurants', ['restaurant_id'], ['id'])
        batch_op.drop_column('restuarant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restuarant_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_restaurant_pizzas_restuarant_id_restaurants', 'restaurants', ['restuarant_id'], ['id'])
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
